// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDIRO1IgMEx1x2LUApylDWUeuHD9OUFk0',
    appId: '1:332028916130:web:c7ef279c3c4679e2ce42fb',
    messagingSenderId: '332028916130',
    projectId: 'rabwa-15ceb',
    authDomain: 'rabwa-15ceb.firebaseapp.com',
    storageBucket: 'rabwa-15ceb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn-xZ2un-WHwRPh9ymfLIEaPBf5jCHYTY',
    appId: '1:332028916130:android:7c63879d0355569fce42fb',
    messagingSenderId: '332028916130',
    projectId: 'rabwa-15ceb',
    storageBucket: 'rabwa-15ceb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5m8WEAMTceyapvzkr0UrvmCYaqORQkzM',
    appId: '1:332028916130:ios:0e8acbac6dfeeaf7ce42fb',
    messagingSenderId: '332028916130',
    projectId: 'rabwa-15ceb',
    storageBucket: 'rabwa-15ceb.appspot.com',
    iosBundleId: 'com.example.rabwa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5m8WEAMTceyapvzkr0UrvmCYaqORQkzM',
    appId: '1:332028916130:ios:793f3c6411ec76c8ce42fb',
    messagingSenderId: '332028916130',
    projectId: 'rabwa-15ceb',
    storageBucket: 'rabwa-15ceb.appspot.com',
    iosBundleId: 'com.example.rabwa.RunnerTests',
  );
}
